### ISSUE TITLE
sendmail 

### ISSUE THREAD

**Issue by ZhiqinYang** [mjholtkamp/submin#8]
hi i think you can add sendmail with ssl smtp, many 25 port is forbidden ！

**Comment by mjholtkamp** [comment]
Hello ZhiqinYang,

I had the same problem. I fixed this by installing an MTA (mail server) on the same machine. That MTA will forward it with SSL or a different port.

I think it's not good to add more complexity to submin, since that goes against the UNIX philosophy of separate building blocks.

So I'm closing this issue as a won't fix, hope that's OK :)
